format
Signed-off-by: Atul-source <atulprajapati6031@gmail.com>

diff --git a/.github/workflows/ci-build.yaml b/.github/workflows/ci-build.yaml
--- a/.github/workflows/ci-build.yaml
+++ b/.github/workflows/ci-build.yaml
@@ -60,20 +60,20 @@ jobs:
           go clean -modcache
 
       - name: Quality Gate - Test coverage shall be above threshold
-	env:
-	    TESTCOVERAGE_THRESHOLD: 0
-	run: |
-	      echo "Quality Gate: checking test coverage is above threshold ..."
-	      echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
-	      totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
-	      echo "Current test coverage : $totalCoverage %"
-	      if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
-		  echo "OK"
-	      else
-		  echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
-		  echo "Failed"
-		  exit 1
-	      fi
+        env:
+            TESTCOVERAGE_THRESHOLD: 0
+        run: |
+              echo "Quality Gate: checking test coverage is above threshold ..."
+              echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+              totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+              echo "Current test coverage : $totalCoverage %"
+              if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+              echo "OK"
+              else
+              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+              echo "Failed"
+              exit 1
+              fi
 
       - uses: dominikh/staticcheck-action@fe1dd0c3658873b46f8c9bb3291096a617310ca6 
         with:
